### ISSUE TITLE
TODO: Complete Workflow

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/dragonjs#1]
- [x] 编写规范注释，选择合适文档生成器
- [x] 编写规范单元测试(Jasmine/PhantomJS)
- [x] 建立持续继承(TravisCI)
- [x] 建立代码覆盖率报告(Bithound)
- [x] [司徒正美 - JavaScript框架设计](https://book.douban.com/subject/25858070/)
### Template
- [x] https://github.com/koajs/koa
- [x] https://github.com/zzo/EventHub
