### ISSUE TITLE
TODO: framework samples

### ISSUE THREAD

**Issue by sabertazimi** [sabertazimi/dragonjs#7]
- [ ] [Cash - jQuery Lite](https://github.com/kenwheeler/cash/blob/master/dist/cash.js)
- [ ] [Real MVC](https://github.com/petermichaux/maria)
- [ ] [MVVM](https://zhuanlan.zhihu.com/p/24475845?utm_source=cn.ticktick.task&utm_medium=social)
- [ ] [简约 React-Like 框架](https://zhuanlan.zhihu.com/p/24007986)
- [ ] [Vue-Like](https://zhuanlan.zhihu.com/p/24435564?utm_source=cn.ticktick.task&utm_medium=social)
